### ISSUE TITLE
Can't get lights at all

### ISSUE THREAD

**Issue by NJman42** [xSnowHeadx/ambi-tv#1]
Hi SnowHead 
 I have gkaindl ambi-tv running great, but when i tried yours every thing seems to be working but i can"t get the lights on at all.Is there a forum we can go to for help!

Thanks for the great work

**Comment by xSnowHeadx** [comment]
Hi,

the main difference to gkaindl's configuration is that you need to specify the type of your led stripe in the config. If these settings are correct, the leds should light without any source when selecting the Moodlight-Mode.
There is a german forum to talk about ambi-tv: http://www.dbox2world.net/board293-cst-coolstream/board297-cst-coolstream-user-cafe/12546-ambi-tv/

regards

**Comment by xSnowHeadx** [comment]
If you are using LPD880x-Stripes, there was an issue in the data output stream for this LED type. This was fixed with the last commit yesterday.
